apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-chart.fullname" . }}-postgresql
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
data:
  JET_AIRBASE_DB_URL: ecto://{{ .Values.postgresqlUser }}:{{ .Values.postgresqlPassword }}@{{ include "jet-chart.fullname" . }}-postgresql:{{ .Values.postgresqlPort | int }}/{{ .Values.postgresqlAirbaseDatabase }}
  JET_AIRBASE_DB_POOL_SIZE: {{ .Values.postgresqlAirbasePoolSize | quote }}
  JET_EVENT_STORE_DB_URL: ecto://{{ .Values.postgresqlUser }}:{{ .Values.postgresqlPassword }}@{{ include "jet-chart.fullname" . }}-postgresql:{{ .Values.postgresqlPort | int }}/{{ .Values.postgresqlEventStoreDatabase }}
  JET_EVENT_STORE_DB_POOL_SIZE: {{ .Values.postgresqlEventStorePoolSize | quote }}
