apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-chart.fullname" . }}-postgresql
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.postgresqlUser }}
  POSTGRES_PASSWORD: {{ .Values.postgresqlPassword | quote }}
  JET_DATABASE_HOST: {{ include "jet-chart.fullname" . }}-postgresql
  POSTGRES_PORT: {{ .Values.postgresqlPort | quote }}
  POSTGRES_DB: {{ .Values.postgresqlAirbaseDatabase }}
  JET_DATABASE_POOL_SIZE: {{ .Values.postgresqlAirbasePoolSize | quote }}
  POSTGRES_EVENT_STORE_DB: {{ .Values.postgresqlEventStoreDatabase }}
  POSTGRES_EVENT_STORE_POOL_SIZE: {{ .Values.postgresqlEventStorePoolSize | quote }}
