apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-chart.fullname" . }}-generic-sonic
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
data:
  JET_SONIC_GENERIC_HOST: {{ include "jet-chart.fullname" . }}-generic-sonic
  JET_SONIC_GENERIC_PORT: "1491"
  JET_SONIC_GENERIC_PASSWORD: {{ .Values.sonicGenericPassword | quote }}
