apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "jet-chart.fullname" . }}-generic-sonic
subsets:
  - addresses:
      - ip: {{ .Values.sonicGenericIP  }}
    ports:
      - port: {{ .Values.sonicGenericPort  }}
