apiVersion: v1
kind: Service
metadata:
  name: {{ include "jet-chart.fullname" . }}-generic-sonic
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 1491
      targetPort: {{ .Values.sonicGenericPort  }}
