apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-chart.fullname" . }}-airbase
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jet.localhost`) && Path(`/api`, `/subscriptions`, `/explorer`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-airbase
          port: 80
    - match: Host(`jet.localhost`) && Path(`/app_store/api`, `/app_store/explorer`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-airbase
          port: 80
    - match: Host(`jet.localhost`) && PathPrefix(`/oss/`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-airbase
          port: 80
