apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-chart.fullname" . }}-jet
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.jetHost }}`) && Path(`/api`, `/explorer`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-airbase
          port: 80
      {{- include "jet-chart.jet-ingress-route-middlewares" . | nindent 6 }}
    - match: Host(`{{ .Values.jetHost }}`) && PathPrefix(`/subscriptions/`, `/live/`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-airbase
          port: 80
      {{- include "jet-chart.jet-ingress-route-middlewares" . | nindent 6 }}
    - match: Host(`{{ .Values.jetHost }}`) && Path(`/app_store/api`, `/app_store/explorer`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-airbase
          port: 80
      {{- include "jet-chart.jet-ingress-route-middlewares" . | nindent 6 }}
    - match: Host(`{{ .Values.jetHost }}`) && PathPrefix(`/oss/`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-airbase
          port: 80
      {{- include "jet-chart.jet-ingress-route-middlewares" . | nindent 6 }}
    - match: Host(`{{ .Values.jetHost }}`) && PathPrefix(`/ops/`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-airbase
          port: 80
      {{- include "jet-chart.jet-ingress-route-middlewares" . | nindent 6 }}
    - match: Host(`{{ .Values.jetHost }}`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-aircrew
          port: 80
      {{- include "jet-chart.jet-ingress-route-middlewares" . | nindent 6 }}
  {{- include "jet-chart.jet-tls-options" . | nindent 2 }}
