apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-chart.fullname" . }}-minio
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`oss.jet.localhost`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-minio
          port: 9090
