apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-chart.fullname" . }}-minio
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.minioHost }}`) && PathPrefix(`/minio/`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-minio
          port: 9090
      {{- include "jet-chart.minio-ingress-route-middlewares" . | nindent 6 }}
    - match: Host(`{{ .Values.minioHost }}`) && PathPrefix(`/{{ .Values.airbaseOSSPrivateBucket }}/`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-minio
          port: 9090
      {{- include "jet-chart.minio-ingress-route-middlewares" . | nindent 6 }}
    - match: Host(`{{ .Values.minioHost }}`) && PathPrefix(`/{{ .Values.airbaseOSSPublicBucket }}/`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-minio
          port: 9090
      {{- include "jet-chart.minio-ingress-route-middlewares" . | nindent 6 }}
  {{- include "jet-chart.minio-tls-options" . | nindent 2 }}
