{{- if .Values.jetTLSSecret | empty | not }}
{{- with .Values.jetTLSSecret }}
{{- if .certificate | empty }}
{{- fail "Please provide `certificate` for jetTLSSecret" }}
{{- end }}
{{- if .key | empty }}
{{- fail "Please provide `key` for jetTLSSecret" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jet-chart.fullname" $ }}-jet-tls-secret
  labels:
    {{- include "jet-chart.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate }}
  tls.key: {{ .key }}
{{- end }}
{{- end }}
