{{- if .Values.minioTLSSecret | empty | not }}
{{- with .Values.minioTLSSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jet-chart.fullname" $ }}-mimio-tls-secret
  labels:
    {{- include "jet-chart.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "Please provide `certificate` for minioTLSSecret" .certificate }}
  tls.key: {{ required "Please provide `key` for minioTLSSecret" .key }}
{{- end }}
{{- end }}
