apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scixir.fullname" . }}-configmap
  labels:
    {{- include "scixir.labels" . | nindent 4 }}
data:
  MIX_LOGGER_LEVEL: {{ .Values.loggerLevel }}
  SCIXIR_MINIO_REDIS_URL: {{ .Values.minioRedisUrl }}
  SCIXIR_MINIO_BROADWAY_LIST_NAME: {{ .Values.minioBroadwayListName }}
  SCIXIR_SCISSOR_BROADWAY_LIST_NAME: {{ .Values.scissorBroadwayListName }}
  SCIXIR_SCISSOR_PROCESSOR_STAGES: {{ .Values.scissorProcessorStages | quote }}
  SCIXIR_VERSIONS: {{ .Values.versions }}
  SCIXIR_MINIO_ACCESS_KEY: {{ .Values.minioAccessKey | quote }}
  SCIXIR_MINIO_SECRET_KEY: {{ .Values.minioSecretKey | quote }}
  SCIXIR_MINIO_SCHEME: {{ .Values.minioScheme }}
  SCIXIR_MINIO_HOST: {{ .Values.minioHost }}
  SCIXIR_MINIO_PORT: {{ .Values.minioPort | quote }}
