apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jet-chart.fullname" . }}-airbase
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jet-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jet-chart.selectorLabels" . | nindent 8 }}
        app: {{ template "jet-chart.fullname" . }}-airbase
    spec:
      {{- with .Values.airbase.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-airbase
          image: {{ include "jet-chart.airbase-image" . }}
          imagePullPolicy: {{ .Values.airbase.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "jet-chart.fullname" . }}-postgresql
            - configMapRef:
                name: {{ include "jet-chart.fullname" . }}-redis
            - configMapRef:
                name: {{ include "jet-chart.fullname" . }}-generic-sonic
            - configMapRef:
                name: {{ include "jet-chart.fullname" . }}-users-names-sonic
            - configMapRef:
                name: {{ include "jet-chart.fullname" . }}-minio
            - configMapRef:
                name: {{ include "jet-chart.fullname" . }}-airbase
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          resources:
            {{- toYaml .Values.airbase.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
