apiVersion: v1
kind: Service
metadata:
  name: {{ include "jet-chart.fullname" . }}-airbase
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    {{- include "jet-chart.selectorLabels" . | nindent 4 }}
    app: {{ template "jet-chart.fullname" . }}-airbase
