apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-chart.fullname" . }}-redis
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
data:
  JET_REDIS_URL: redis://{{ include "jet-chart.fullname" . }}-redis:6379
  JET_REDIS_POOL_SIZE: {{ .Values.redisPoolSize | quote }}
