apiVersion: v1
kind: Service
metadata:
  name: {{ include "jet-chart.fullname" . }}-redis
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 6379
      targetPort: {{ .Values.redisPort }}
