apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-chart.fullname" . }}-users-names-sonic
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
data:
  JET_SONIC_USERS_NAMES_HOST: {{ include "jet-chart.fullname" . }}-users-names-sonic
  JET_SONIC_USERS_NAMES_PORT: "1491"
  JET_SONIC_USERS_NAMES_PASSWORD: {{ .Values.sonicUsersNamesPassword | quote }}
