apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "jet-chart.fullname" . }}-users-names-sonic
subsets:
  - addresses:
      - ip: {{ .Values.sonicUsersNamesIP  }}
    ports:
      - port: {{ .Values.sonicUsersNamesPort  }}
