apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-chart.fullname" . }}-minio
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
data:
  MINIO_ACCESS_KEY: {{ .Values.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minioSecretKey | quote }}
  JET_MINIO_SCHEME: {{ .Values.minioScheme }}
  JET_MINIO_HOST: {{ .Values.minioHost }}
  JET_MINIO_PORT: {{ .Values.minioPort | quote }}
