apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "jet-chart.fullname" . }}-minio
subsets:
  - addresses:
      - ip: {{ .Values.minioServiceIP }}
    ports:
      - port: {{ .Values.minioServicePort }}
