apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "jet-chart.fullname" . }}-minioredis
subsets:
  - addresses:
      - ip: {{ .Values.minioredisIP }}
    ports:
      - port: {{ .Values.minioredisPort }}
