version: '3.2'
networks:
  external-services-network: {}
services:
  # minio
  minio:
    image: minio/minio:RELEASE.2020-10-27T04-03-55Z
    env_file:
      - external-services.env
      - external-services.local.env
    command: server --address :9090 /data
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - external-services-network
  # postgresql
  postgresql:
    image: byzanteam/postgres-zhparser-alpine:latest
    env_file:
      - external-services.env
      - external-services.local.env
    volumes:
      - ./volume/config/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./volume/config/postgresql:/usr/local/etc/postgresql
    entrypoint: []
    command:
      - sh
      - -c
      - |
        chown postgres $$POSTGRES_CONFIG_PATH
        docker-entrypoint.sh postgres -c config_file=$$POSTGRES_CONFIG_PATH
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - external-services-network
  # sonic
  sonic:
    image: valeriansaliou/sonic:v1.3.0
    env_file:
      - external-services.env
      - external-services.local.env
    volumes:
      - ./volume/config/sonic/generic.cfg:/etc/sonic.cfg
    restart: unless-stopped
    ports:
      - 1491:1491
    networks:
      - external-services-network
