version: '3.2'
services:
  minio:
    image: minio/minio:RELEASE.2022-03-24T00-43-44Z
    volumes:
      - ./volume/data/minio/data:/data
    env_file:
      - external-services.env
      - external-services.local.env
    command: server --address :9090 /data
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - external-services-network
