version: '3.2'
services:
  generic_sonic:
    image: valeriansaliou/sonic:v1.3.0
    env_file:
      - external-services.env
      - external-services.local.env
    volumes:
      - ./volume/config/sonic/generic.cfg:/etc/sonic.cfg
      - ./volume/data/sonic/store/generic/:/var/lib/sonic/store/
    restart: unless-stopped
    ports:
      - 1491:1491
    networks:
      - external-services-network
  users_names_sonic:
    image: valeriansaliou/sonic:v1.3.0
    env_file:
      - external-services.env
      - external-services.local.env
    volumes:
      - ./volume/config/sonic/users_names.cfg:/etc/sonic.cfg
      - ./volume/data/sonic/store/users_names/:/var/lib/sonic/store/
    restart: unless-stopped
    ports:
      - 1492:1491
    networks:
      - external-services-network
